Cycle execution times: 1  #程序循环执行的次数
switch_node:  #交换机信息
  ip: #ip
  username: #用户名
  password: #密码
test_node:  #主要被测节点，可以添加若干台
  - name: #节点名
    ip: #节点ip
    bond_ip:  #bondip
    username: #用户名
    password: #密码
    bond_name:  #bond名
    port_name:  #port名
    sub_bond_name:
      sub1: #组成bond的其中一张子网卡名
      sub2: #组成bond的其中一张子网卡名
other_node: #辅助测试节点
  - name: #节点名
    ip: #节点ip
    username: #用户名
    password: #密码

